
project_id = "onwthrpgcnfydxzzmyot"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.transcribe-video]
verify_jwt = true

[functions.access-file]
verify_jwt = false

[functions.access-message]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.send-reminder-emails]
verify_jwt = false
import_map = ["./import_map.json"]

[functions.send-message-notifications]
verify_jwt = false
import_map = ["./import_map.json"]

[functions.send-test-email]
verify_jwt = false
import_map = ["./import_map.json"]

