
project_id = "onwthrpgcnfydxzzmyot"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

# Functions config section
[functions]
[functions.access-message]
verify_jwt = false

[functions.enhance-message]
verify_jwt = false

[functions.location-services]
verify_jwt = false

[functions.process-video]
verify_jwt = false

[functions.send-message-notifications]
verify_jwt = false

[functions.send-reminder-emails]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
